# Generated by Django 2.0.5 on 2018-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
